# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve --livereload'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jing Jie's Portfolio
email: jingjie105@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my website where I showcase my portfolio consisting of my projects that I have done over the years and more.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://lamjingjie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: lam-jing-jie-5720771aa/
github_username:  LamJingJie
# Fields minima uses, but are not defaulted with the jekyll new command.
author: Jing Jie

# Images for the site

tldraw_img:
    -
        index: 1
        img_name: "pic1.png"
        width: "60%"
    -
        index: 2
        img_name: "pic2.png"
        width: "60%"
    -
        index: 3
        img_name: "pic3.png"
        width: "60%"
    -
        index: 4
        img_name: "pic4.png"
        width: "80%"


tlextractor_img:
    -
        index: 1
        img_name: "pic1.png"
        width: "60%"
    -
        index: 2
        img_name: "pic2.png"
        width: "60%"
    -
        index: 3
        img_name: "pic3.png"
        width: "60%"
    -
        index: 4
        img_name: "pic4.png"
        width: "80%"
    -
        index: 5
        img_name: "pic5.png"
        width: "80%"

varbot_img:
    -
        index: 1
        img_name: "Varbot_Home_1.png"
        width: "100%"
    -
        index: 2
        img_name: "Varbot_Home_2.png"
        width: "100%"
    -
        index: 3
        img_name: "Varbot_Home_3.png"
        width: "100%"
    -
        index: 4
        img_name: "Varbot_Home_4.png"
        width: "100%"
    -
        index: 5
        img_name: "Varbot_Home_5.png"
        width: "100%"

propertyNoti_img:
    -
        index: 1
        img_name: "propertynoti1.jpg"
        width: "40%"
    -
        index: 2
        img_name: "propertynoti2.jpg"
        width: "40%"
    -
        index: 3
        img_name: "propertynoti3.jpg"
        width: "40%"
    -
        index: 4
        img_name: "propertynoti4.jpg"
        width: "40%"
    -
        index: 5
        img_name: "propertynoti5.jpg"
        width: "40%"
    -
        index: 6
        img_name: "propertynoti6.jpg"
        width: "40%"
    -
        index: 7
        img_name: "propertynoti7.jpg"
        width: "40%"
    -
        index: 8
        img_name: "propertynoti8.jpg"
        width: "40%"

treat_image:
    -
        index: 1
        img_name: "treat_0.png"
        width: "40%"
    -
        index: 2
        img_name: "treat_1.png"
        width: "40%"
    -
        index: 3
        img_name: "treat_2.png"
        width: "40%"
    -
        index: 4
        img_name: "treat_3.png"
        width: "40%"
    -
        index: 5
        img_name: "treat_4.png"
        width: "40%"
    -
        index: 6
        img_name: "treat_5.png"
        width: "40%"
    -
        index: 7
        img_name: "treat_6.png"
        width: "40%"

tpopenhouse_image:
    -
        index: 1
        img_name: "tpopenhouse_stats_android.png"
        width: "100%"
    -
        index: 2
        img_name: "tpopenhouse0.png"
        width: "100%"
    -
        index: 3
        img_name: "tpopenhouse1.png"
        width: "30%"
    -
        index: 4
        img_name: "tpopenhouse2.png"
        width: "30%"
    -
        index: 5
        img_name: "tpopenhouse3.png"
        width: "72%"
    -
        index: 6
        img_name: "tpopenhouse4.png"
        width: "72%"
    -
        index: 7
        img_name: "tpopenhouse5.png"
        width: "30%"
    -
        index: 8
        img_name: "tpopenhouse6.png"
        width: "72%"
    -
        index: 9
        img_name: "tpopenhouse7.png"
        width: "60%"
    -
        index: 10
        img_name: "tpopenhouse8.png"
        width: "60%"
    -
        index: 11
        img_name: "tpopenhouse9.png"
        width: "60%"
    -
        index: 12
        img_name: "tpopenhouse10.png"
        width: "30%"
    -
        index: 13
        img_name: "tpopenhouse11.png"
        width: "60%"
    -
        index: 14
        img_name: "tpopenhouse12.png"
        width: "60%"

# Build settings
# Removed Minima theme as it is now a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
